### ISSUE TITLE
Building with TC 2.01

### ISSUE THREAD

**Issue by andrewbird** [FDOS/share#2]
I mentioned in https://github.com/FDOS/kernel/issues/43 that I'd like to be able to build share at the same time as the kernel. For me it probably means getting it to cross compile with Watcom or Gcc-ia16-elf. As a precursor to that work I thought I'd try compiling with tcc as a reference. TC++ 3.0 didn't work as you mentioned and after fiddling with that a long time, I switched to TC 2.01. The thing is I can't get that to work either, even using your latest build method. This is the result.
~~~
F:\>make
c:\tc201\tcc -c -mt -1 -Ic:\tc201\include share.c
Turbo C  Version 2.01  Copyright (c) 1987, 1988 Borland International
share.c:
 
        Available memory 440450
c:\tc201\tlink /m /s /c /t c:\tc201\lib\c0t.obj share.obj,share.com,,c:\tc201\lib\cs.lib
Turbo Link  Version 2.0  Copyright (c) 1987, 1988 Borland International
Undefined symbol '_main' in module C0T
make.exe: *** [makefile:31: SHARE.COM] Error 1  
~~~

Did you see anything similar, if so how did you overcome it?

**Comment by andrewbird** [comment]
Note that a share.com file is produced but it's non functional at around 1.7k bytes, whereas the one in FreeDOS 1.2 release is 6k bytes.

**Comment by andrewbird** [comment]
Found it! I got caught out by TC 2.01 not processing files with Unix line endings, just silently ignoring the content. Sorry for the noise.

**Comment by PerditionC** [comment]
Glad you figured it out.  :-)
